version: '3.8'

services:
  chatbot:
    build: .
    container_name: chatbot_api
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY=SUA_API_KEY_AQUI  # Use ENV para maior segurança
