# Docker Compose Configuration
version: '3.8'

services:
  chatbot:
    build: .
    container_name: chatbot_api
    ports:
      - "5000:5001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}  # Usa variável de ambiente para segurança
    deploy:
      resources:
        limits:
          cpus: "0.2"    # Limita a 200 MHz (0.2 de um core)
          memory: "2g"   # Limita a 2GB de RAM
